import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { Header } from "@/components/Header";
import { AppProvider } from "@/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "E-Commerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-slate-500 p-6`}>
				<AppProvider>
					<Header />
					<Nav />
					{children}
				</AppProvider>
			</body>
		</html>
	);
}
